final

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -55,7 +55,11 @@ jobs:
           echo "fastapi-backend logs:"
           docker logs fastapi-backend || echo "Unavailable"
 
-  
+      - name: Wait and Health Check
+        run: |
+          sleep 10
+          docker ps
+          curl --fail http://localhost:8003 || (echo "FastAPI failed to start" && exit 1)
 
   deploy:
     name: Deploy (Same Runner)
